
-- Fact: post-level metrics table
CREATE TABLE IF NOT EXISTS POSTS(
    ID TEXT PRIMARY KEY,
    TITLE TEXT,
    AUTHOR TEXT,
    FLAIR TEXT,
    SELFTEXT TEXT,
    SUBREDDIT TEXT,
    SCORE BIGINT, 
    AI_SENTIMENT TEXT,
    AI_REASPNING TEXT,
    NUM_COMMENTS BIGINT,
    CREATED_UTC TIMESTAMPTZ,
    PROCESSING_TIMESTAMP TIMESTAMPTZ NOT NULL DEFAULT now()
)

-- Fact: comments-level data
CREATE TABLE IF NOT EXISTS COMMENTS(
    ID TEXT PRIMARY KEY,
    POST_ID TEXT NOT NULL 
            REFERENCES POSTS(ID)
            ON DELETE CASCADE,
    PARENT_ID TEXT,
    BODY TEXT,
    AUTHOR TEXT,
    SCORE BIGINT,
    CREATED_UTC TIMESTAMPTZ,
    PROCESSING_TIMESTAMP TIMESTAMPTZ NOT NULL DEFAULT now()
)
